### ISSUE TITLE
[3] Provide email status notifications for harvests

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#11]
# Summary

Questions to write summary: 
Who they should notify? 
When notifications send (what prompts a notification) - state of import? 
What is the language of the notification? What is the content of the notification? 
How are notification sending - in app or in email? 
Can people turn off notifications? 
What does the notification make people do? 

# Acceptance Criteria
- [x] Upon completion of an import, email the curator or admin who set up the harvest to notify them it has completed.  
- [x] Language matches the messages sent in the current app.  (Look to code and add details for testing). 
- [ ] Uses existing code and language in new app.  

# Testing Instructions

Do a sample harvest.  
- [x] Confirm that confirmation message is sent in email
 
# Notes
This ticket also relates to #17

**Comment by bkiahstroud** [comment]
Initial investigation points to this previously being accomplished by the `JobLogEntry` model (see #17). In Spotlight 3.3.0, the `JobLogEntry` model has been replaced in favor of a new `JobTracker` model

**Comment by summer-cook** [comment]
Notes:

Spotlight uses ActionMailer: https://github.com/projectblacklight/spotlight/blob/b06511be2b93a1dd999aada2405ab8609592804f/README.md#default-actionmailer-configuration

**Comment by sephirothkod** [comment]
@dl-maura has this been tested? Did it work with the ENV settings that you were updating?

**Comment by dl-maura** [comment]
It didn't when I tried adding those variables and setting things in the environment file but I'm trying something else today, will keep you posted

**Comment by dl-maura** [comment]
I'm not sure what existing code and language means? Separate from language in the email which was already its own checkbox?

**Comment by enriquediaz** [comment]
I can see the source of the confusion, where "language" appears in both bullets and context implies each has a different meaning. It's also possible @crisr15 included it in both bullets in the original description unintentionally. Crystal, might you have some insight or recollection about that third bullet?

**Comment by crisr15** [comment]
This was just poor phrasing on my part.  Language should have been replaced with something like "body of text".  Basically we needed to go and look at code from the old app to see what the messages were that need to be sent and confirm that we are sending the same messages following the same activities.  Or look at old app, check what notifications sent, make them send again in the new application.

**Comment by dl-maura** [comment]
@VanessaVenti We're closing this but if there are other processes that need notification emails, please let us know to make a new ticket. We are consistently seeing emails for harvesting
