### ISSUE TITLE
Set up Harvesting

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#13]
# Summary

Questions for filling out Summary: 
How does the JSON come into play?  
Is other format XML? 
Can we get a link to the custom OAI plugin code and a run through of how it is working? 

# Video of Harvesting working in 2.7 curiosity
https://harvard.zoom.us/rec/share/TkEMWY3r9Vo1-d2e3TSyFrGrLAHxfVZrYnXy6DU-DpbaLoSataAn4aZ-aIosoyeP.bJAR3ShRmkcm5xRh

# Ticket Breakdown
- [x] Bring in the harvesting gem, set it to pull from the `main` branch
- [x] Set up `delayed_job` in its own worker container and add `delayed_job_web` gem
- [x] Find out why items are not harvesting even though the PerformHarvestsJob says complete with no errors
- [x] Replace Job Log Entries with Job:Trackers in the oaipmh gem in order to track the reindexing/harvesting of items in the dashboard in the UI
- [x] Bring over any UI elements that are in the `job-entry` branch to make sure users can see the reindexing and harvesting in the Dashboard

# Acceptance Criteria
- [x] As a user, i can harvest items in the dashboard
- [x] As a user, i can see the items updating in the dashboard as I harvest or reindex them.

# Testing instructions

# Notes 

OAI gem: https://github.com/harvard-lts/spotlight-oaipmh-resources -

it utilizes delayed jobs so we will need to set that up 

Spotlight ETL PR: https://github.com/projectblacklight/spotlight/pull/2625/files#diff-c02930cd62f71f8205819214163e2ed950cb8cd774f71eaaaa4f71466523ef4a

**Comment by VanessaVenti** [comment]
@bkiahstroud - The Acceptance Criteria items look good to me, but I see there are a few unchecked items under Ticket Breakdown. Are these done? If so, I'm happy to check off the Acceptance Criteria items and close this story.

**Comment by bkiahstroud** [comment]
@VanessaVenti yes, I think we just forgot to come back and check those off. They have been completed.

**Comment by VanessaVenti** [comment]
Great, I'll go ahead and close this one then.
