### ISSUE TITLE
Write "Self-help" documentation

### ISSUE THREAD

**Issue by jeremyf** [harvard-lts/CURIOSity#147]

**Comment by jeremyf** [comment]
This ticket is to provide documentation for the following issues:

- [ ] #134 Adjusting metadata labels
- [ ] #136 Adjusting default fields
- [ ] #135 Addressing duplicate fields

The documentation will:

- [ ] Reference "best effort" code changes that addressed the above listed tickets; providing a "live" example of how to do it
- [ ] Be added to the Spotlight/Blacklight wiki's and referenced in this issue; providing an example for future adopters to reference

*Note: "best effort" is following the guidance provided in the tickets to move things towards their desired state, but more importantly to demonstrate how other folks can also make adjustments.*

**Comment by jeremyf** [comment]
The current "draft" documentation can be found in the following commit's message: https://github.com/harvard-lts/CURIOSity/commit/b1cdb9fe74076dac82538d6167eba48c73d660bd

**Comment by VanessaVenti** [comment]
@dl-maura and @phil-plencner-hl - I think this one is for you both to test.

**Comment by dl-maura** [comment]
Maura C. will want to get this into the Harvard wiki

**Comment by dl-maura** [comment]
Maura will put example of solr harvest slice in docs

**Comment by VanessaVenti** [comment]
@dl-maura can this one be closed?
