### ISSUE TITLE
FTS results aren't displaying

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#156]
## Summary

Demo of bug here: https://drive.google.com/file/d/1tqMkNZXCBt761RhYmbVfswwdzVvk5NN1/view

## Acceptance Criteria 

Search results render in the UI when:

- [ ] Performing a FTS 
- [ ] When changing the Per Page limit 
- [ ] When navigating the pagination 

## Testing Instructions 

1. Login as an admin 
2. Create a new exhibit and harvest the contagion set 
3. After the harvest completes, perform a FTS for "hospital" or "epidemic" 
4. Validate the Acceptance Criteria

**Comment by sephirothkod** [comment]
seems like urns are not being loaded during first OAI harvest, so the search gets many FTS results but can't connect them to resources that have been imported.

**Comment by sephirothkod** [comment]
a fix for this is ready in the oai gem.

**Comment by bkiahstroud** [comment]
Initial testing with the new change shows that URNs are successfully being persisted on the solr doc sidecars, but FTS results are still empty in the UI: 

![hospital - contagion-test - Harvard Curiosity Search Results 2022-08-29 at 11 11 31 AM](https://user-images.githubusercontent.com/32469930/187269724-98794d86-9459-4cfd-a6dd-4751fe6cab58.jpg)

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/145

**Comment by dl-maura** [comment]
@bkiahstroud I see you mentioned referencing the testing instructions but I don't see any? What should I be looking for?

**Comment by bkiahstroud** [comment]
@dl-maura whoops, I forgot to add them after writing that. I just added them to the ticket's description.

**Comment by summer-cook** [comment]
### Passed: Notch8 QA

I can see the FTS results after harvesting contagion

- [ ]  Performing a FTS
- [ ]  When changing the Per Page limit
- [ ]  When navigating the pagination

![Image](https://user-images.githubusercontent.com/73361970/187797763-4bad7002-75cc-4d16-964b-6b37caa307f0.png)

**Comment by dl-maura** [comment]
Results are displaying, there may be a secondary issue with what is in the results but that will be a new ticket.
