### ISSUE TITLE
Replace deprecated JobLogEntry with JobTracker

### ISSUE THREAD

**Issue by crisr15** [harvard-lts/CURIOSity#17]
### Current work: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/7 

# Summary

This functionality appears equivalent to the background job monitoring
that has been added to spotlight since the Job Log was developed. We recommend adding the notifications that are required during harvest to the new job monitoring instead of maintaining this divergence.

# Acceptance Criteria

_Verify the following data gets populated under the "Recent item indexing activity" section in the Exhibit Dashboard when running a harvester_

- [x] Date
- [x] Requested by
- [x] Items indexed (after harvest completes/fails) 
- [x] Elapsed time (after harvest completes/fails)
- [x] Status 
  - [x] Progress logged every 100 items 

<details><summary>Screenshots</summary>

![Curation - Dashboard Contagion - Notch8 Staging 2022-09-06 at 8 16 07 AM](https://user-images.githubusercontent.com/32469930/188672653-58f5bc55-345d-440a-a389-ecb0649f8628.jpg)

![Curation - Dashboard Contagion - Notch8 Staging 2022-09-06 at 8 16 56 AM](https://user-images.githubusercontent.com/32469930/188672664-283e0859-4955-4fc6-b38c-08292e034d86.jpg)

</details>

## Discovery

- No custom UI elements; uses existing Spotlight UI 
  - Mainly, [app/views/spotlight/dashboards/_reindexing_activity.html.erb](https://github.com/projectblacklight/spotlight/blob/v3.3.0/app/views/spotlight/dashboards/_reindexing_activity.html.erb) and [app/views/spotlight/catalog/_reindex_progress_panel.html.erb](https://github.com/projectblacklight/spotlight/blob/v3.3.0/app/views/spotlight/catalog/_reindex_progress_panel.html.erb)
- UI in Spotlight 2.7.0 looked at `JobLogEntry` model; now looks at `JobTracker` model in 3.3.0

**Comment by VanessaVenti** [comment]
@dl-maura and @phil-plencner-hl looks like this one is for you to test/confirm.

**Comment by dl-maura** [comment]
@bkiahstroud If this is implemented, is the test just confirm harvest still works?
