### ISSUE TITLE
Design refinements: masthead, teal nav, and other general styles

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#172]
### Masthead (Exhibit pages)
- [x] Keep same spacing below title whether there is a subtitle or not (MF: set this height to 360px and vertically centered text, should be good once the search box is inline with the nav)
- [x] Exhibit titles and subtitle text adjusted to match other L.H pages

Note: may want to make further adjustments once we have a better idea and design for how we want to treat the search box

### Nav bar
- [x] Align with left nav box and match on right, [see screenshot](https://user-images.githubusercontent.com/60190174/176771731-8c908b8d-0cb3-4871-999c-1dd4ec43f001.png). 
- [x] ~~Reduce length of search box by a third (this has to be reworked a bit, as search box style and placement has changed since introducing FTS checkbox)~~
- [x] New nav/searchbox [pattern](https://marvelapp.com/prototype/d9c9j0b/screen/88490107/handoff):
   - [x] Transparent black background
   - [x] Search box in line with nav items
   - [x] Search icon switch to text "Search"
   - [x] If FTS is available, checkbox and text appears as a popout below search box
   - [x] Increase opacity of dropdown background and FTS search area by half

#### (MF addition) Style nav to match Library.Harvard jump links [(example)](https://library.harvard.edu/how-to/borrow-renew-and-return-library-materials)
- [x] More padding around links
- [x] Add white bottom-border to hover and active states (also exists on current site)

#### (MF addition) Cleanup dropdown + subpages
- [x] Remove the whitespace/small gap when the dropdown opens
- [x] Adjust subpage margins on mobile (pushed too far left)

Note: Teal part lines up similar to how nav aligns with text on Library.Harvard, though may not look that way with the black searchbox at the moment

### Favicon
- [x] Update favicon to use HL logo

### Child theme header
- [x] Adjusted height and font sizes to match HGL child theme header bar
- [x] Vertically centered the HL logo and username
- [x] Username restyle (reduce letter-spacing, make white for better color contrast)

### Login/Sign up/Forgot password pages
- [x] Input fields weren't pulling in our bootstrap styles like other input fields (on the admin side), because don't have class = "form-control" on their inputs; i targeted these specifically to look like the others (Trueno font, more rounded borders, better spacing between elements, etc.)
- [x] Center forms on page

### Site homepage (logged in state)
- [x] Card description font-size - make smaller on smaller screens (13px, figure out good breakpoint for this)
- [x] Make "Create a new exhibit" button stand out more (solid, black style)
- [x] Nav-heading ("Actions") switched to an h2 (is tagged as an h4 in vanilla spotlight) and restyled (remove bottom border, bold, uppercase, normal letter-spacing)
- [x] Nav-links in sidebar reset to have normal letter-spacing
- [x] "Curator Documentation" link: ~~open in a new tab~~ + add an external link icon *for accessibility reasons, it's best to not open tabs in new windows by default
- [x] Make "View as" dropdown menu wider so that "Exhibit Admin" doesn't wrap to two lines
- [x] Consistently two h1's on each admin page, found file with h1 class="page-header" and switched it to an h2, sizing feels a lot better for these now (Customize Appearance, Order Exhibits, Manage Users)

### Alerts and cards
- [x] Change to Trueno font
- [x] Danger Alert box links are now black with gray bottom border (the blue had contrast issue with red background); example is under the "Delete Exhibit" tab on the General admin page
- [x] Changed $info variable to be gray #6c6c6c (vs. the lighter blue it was pulling in, #2797d8) to better go with our theme - open to switching this back! (mostly effects our info alert boxes and cards)
- [x] Close button (remove border and change opacity on hover)

### Other miscellaneous styles
- [x] Nav-link tabs (see these a lot in admin views) - gave a darker outline, black text in active state, less letter-spacing, uppercase
- [x] Made the $secondary variable $black (vs. gray) to match our HL theme buttons; hover and active states are dark gray
- [x] Reorganized the order of imported style files (application.scss and spotlight.scss) so harvard stuff was at the top and being pulled in as bootstrap overrides - you can tell not everything is getting overriden because in inspect mode, if you scroll to the bottom you will see that the :root colors are bootstrap default, not our harvard colors
- [x] Exhibit dashboard - .page-header is now an H2 and the .small text within in is restyled (capitalized, normal letter-spacing, semibold)
- [x] Remove @import 'harvard-bootstrap' from the top of each custom scss file (if 'harvard-bootstrap' is imported first, then you don't need to keep adding this)
- [x] Make body font "Lora" (currently using "Georgia")

Active branch: FE-172

**Comment by mferrarini** [comment]
Restyled alert box with black links example: ![Screen Shot 2022-09-06 at 4 23 49 PM](https://user-images.githubusercontent.com/13121501/188731338-7fa9ac87-893a-4914-9f2d-4ffe1dbacaaa.png)

**Comment by enriquediaz** [comment]
@VanessaVenti I've reviewed the tasks listed out in this ticket and have verified they conform with technical specifications and design intent. I think the work in this task can be considered complete. Great work @mferrarini!
