### ISSUE TITLE
Design refinements: exhibit admin pages

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#177]
## Sidebar menu and page titles
- [x] Increase padding to the bottom of each section of the left [see screenshot](https://user-images.githubusercontent.com/60190174/176682362-6460c2b5-008d-4966-9618-e57efdf8f12e.png)
- [x] Eliminate letter spacing where text is proper case (also seen in Title, username, and left nav child page links)
- [x] Style .page-header as an H2
- [x] Style .page-header small as an H3
- [x] "Analytics" link: ~~open in a new tab~~ + add an external link icon (fixed this alongside another external link for "Curator documentation") *for accessibility reasons, it's best to not open tabs in new windows by default
- [x] Prevent hover state from spanning the entire column

## Tables
- [x] Make borders consistent with what see on other pages, like "Mange users"
- [x] Trueno font (for consistency)
- [x] Table headers: regular capitalized case, normal letter-spacing
- [x] Smaller font size for "View" and "Edit" links
- [x] Match Item Titles with search results styling (letter-spacing and line-heights look they they need to be adjusted)

## Dashboard
- [x] Still has “Curation” title above it - if it’s not underneath the “Curation” section anymore we should consider changing this
- [x] Change H2's to H3's (Recent ____ headings)
- [x] More padding between sections?
- [x] Tables
    - [x] change to Trueno font
    - [x] Change titles (h4s) so regular capitalized case, normal letter spacing, etc. (maybe like we have styled under Items, but keep black)
    - [x] Smaller View/Edit links, remove padding

## Configuration: General
- [x] Rename **Set Name** to **FTS Set Name** to distinguish it from the LibraryCloud set name
- [x] Add exhibit ID back under General, see screenshot of 2.0 below:
![](https://user-images.githubusercontent.com/60190174/184240477-2063d7d8-07a2-4d86-a11c-76e20dc3e711.png)
- [x] Make sure input fields are consistent with other pages (should be pulling in our custom bootstrap for this) *look at this across all tabs
- [x] Make "Import Data" button look like it's connected to the browse input field
- [x] "Add New Recipient" button needs a hover/focus state

## Configuration: Appearance
- [x] Main menu tab: letter-spacing and format of page titles
- [x] Main menu tab: make pencil icon more visible on hover (i.e. darker)

## Configuration: Metadata
- [x] Prevent "Select All" button from wrapping to 2 lines (give it the small button treatment)
- [x] Prevent jumpiness that happens when text is wrapped for the “field name”, then hover to reveal the edit pencil **still sometimes jumps to the right, but better than before
- [x] Make pencil appear when hovering over the field name, not the reordering icon to the left of field name
- [x] Exhibit-specific fields table style updates (smaller edit and delete links, bolder field label?)

`<%= exhibit_edit_link field %> &middot;
<%= exhibit_delete_link field %>`

## Configuration: Search
- [x] Give more padding above the “Save changes” button to prevent from looking like it's just misaligned with the "Add new field" button
- [x] Facets tab: spruce up dropdown carot (made dark gray)

## Configuration: Items
- [x] Still has “Curation” heading even though moved to “Configuration” (2 files that needed this change)
- [x] Make “# per page” dropdown the same height and style as “Sort by Timestamp”
- [x] “Reindexing status” box (appears after clicking "Reindex items" button)
    - [x] remove teal color by changing $info color to $gray-600 (#6c6c6c) in harvard-bootstrap

## Configuration: Tags
- [x] Move under curation

## Configuration: Bulk Updates
- [x] Move under curation
- [x] Download CSV tab
    - [x] Change check box defaults so that Visibility is UNchecked and Tags is CHECKED. (Curators are much more likely to update Tags rather than Visibility). If this is difficult to find /update in the code, this task is a low priority so it can be left to the end.
    - [x] Fix spacing between heading sections

## Curation: Browse
- [x] "Edit" browse category
    - [x] Hide the Masthead tab so curators cannot change the masthead for a browse category. This is bad practice from a usability standpoint (hidden from everyone for now). 
    - [x] "Cancel" button cleanup
- [x] Table needs sprucing up
    - [x] Titles
    - [x] Smaller font for links
    - [x] why is some in italics and some not? make more consistent
    - [x] make .d-flex box width the same for all cards, regardless of content inside it

## Curation: Featured pages
- [x] Table titles formatting

## Curation: About pages
- [x] Contact card restyles (bold name, smaller link text)

Active branch:

**Comment by phil-plencner-hl** [comment]
MR for "Add exhibit ID back under General" here: 
https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/182

**Comment by mferrarini** [comment]
Pulling out the unfinished tasks and moving this to Harvard QA for the rest to be tested.

**Comment by enriquediaz** [comment]
@VanessaVenti I was able to verify every task @mferrarini listed in this issue has been done and appears in QA as desired. I think this can be considered completed and closed.
