### ISSUE TITLE
FTS Search Results -- Pagination/Result Number Issue

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#178]
We're seeing inconsistencies and errors with he results listing for FTS searches, see this video for a walkthrough:
https://drive.google.com/file/d/1okzvPe8PXUp4S4Dmt7SaksLminYlg6AT/view?usp=sharing

- [x] Implement "infinite scroll" pagination 
- [x] Decide what default number to set and make new ticket (https://github.com/harvard-lts/CURIOSity/issues/216)

<details><summary>Archived</summary>

Investigate incorrect behavior and determine whether or not they're caused by the data inconsistencies between CURIOUSity and the FTS data set.

- [ ] Incorrect facet counts (?) 
- [ ] Empty results pages 
- [ ] `403` errors sometimes thrown on the last page(s) of FTS results 

</details>

**Comment by VanessaVenti** [comment]
Available To is actually not an accurate count of how many items are in the results bc of discrepancies in our metadata. I think we need to be able to see the total number of search results to test searching accurately. See this story here which I just created: https://github.com/harvard-lts/CURIOSity/issues/179

**Comment by sephirothkod** [comment]
Well I think I know all the answers here!

This is mostly the FTS solr (including the 403 which is a direct error from the FTS solr instance). The total results number being returned is incorrect, directly from the FTS solr so we get the wrong number of pages (empty pages) and the more empty pages we get, the more likely we are to see the 403 error.

The only thing that might not be the FTS solr is the facet numbers being wrong. That is because in order to get the correct numbers we would have to pull all 700 (or however many) results from FTS, match them to their local counterparts and then get the local solr facets from there. which would likely be way too long of a loading time (we are talking minutes of waiting). 

The best solution is to remove the facets all together, or we can continue to display the metadata search facets as we are doing now.

**Comment by bkiahstroud** [comment]
@VanessaVenti just tagging you to make sure you see Braydon's response above ☝

**Comment by phil-plencner-hl** [comment]
I was looking into how FTS results are displayed for a couple of examples in Contagion today. Specifically searching for "hospital" and "epidemic":

- https://curiosity-qa.lib.harvard.edu/contagion/catalog?exhibit_id=contagion&search_field=all_fields&q=hospital&fulltext=yes
- https://curiosity-qa.lib.harvard.edu/contagion/catalog?exhibit_id=contagion&search_field=all_fields&q=epidemic&fulltext=yes

In both cases we are seeing what Maura describes above. There are more pages than results and the facets are inaccurate. I understand what @sephirothkod  is saying about how it's using the full number from FTS which could be causing the discrepancy.

However, the interesting thing about both searches is that everything in the facets appears to be exactly double from when you do a regular search:

- https://curiosity-qa.lib.harvard.edu/contagion/catalog?exhibit_id=contagion&search_field=all_fields&q=hospital
- https://curiosity-qa.lib.harvard.edu/contagion/catalog?exhibit_id=contagion&search_field=all_fields&q=epidemic

For example the "Place of Origin" Facet for `hospital` without FTS:

- Massachusetts 42
- England 22
- London 20
- District of Columbia 14
- New York State 14
- New York 11
- Pennsylvania 11
- Boston 10
- Washington 10
- Philadelphia 9

Same facet for `hospital` with FTS:

- Massachusetts 84
- England 44
- London 40
- District of Columbia 28
- New York State 28
- New York 22
- Pennsylvania 22
- Boston 20
- Washington 20
- Philadelphia 18

They are all exactly double. All the other facets for the search also exactly double. The facets exactly double for `epidemic` as well. This seems to me more than mere coincidence. 

Additionally, the pager seems to be doubled in size for the result sets. For `hospital` it thinks there are 12 pages of results when there really are only 6.5. Similar doubling of the pager happens for `epidemic`. 

I'll also note that the facet itself doesn't seem to be filtering at all (apologies if Maura C. already mentioned this in her video, as it's been a while since I watched it earlier today so I don't remember all the details contained within). Selecting `Philadelphia" does not filter it down to 18 items, it still displays them all:
https://curiosity-qa.lib.harvard.edu/contagion/catalog?f%5Bplace-of-origin_ssim%5D%5B%5D=Philadelphia&fulltext=yes&q=hospital&search_field=all_fields

Spotlight should still know the item's metadata even if it's adding the additional FTS data to its results, no? The facets should still be able to work off of that existing metadata.

Spotlight should also still know the number of items (as opposed to FTS "hits") in its result set as well. For example, in the list of results we've broken down how many instances of the FTS search appear in each item when it displays messages like "Matches in Full Text (1 of 37)". Seems like we could leverage this in some way to get it properly displaying results / facets / pages.

Thoughts? @bkiahstroud @dl-maura @enriquediaz

**Comment by enriquediaz** [comment]
Yes! If the pagination and facet counts the user sees when a full-text + metadata search is performed can continue to reflect the metadata results counts, we'll arrive at the desired experience.

**Comment by bkiahstroud** [comment]
Related MR: https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/173

**Comment by bkiahstroud** [comment]
GitHub PR: https://github.com/harvard-lts/CURIOSity/pull/206

**Comment by VanessaVenti** [comment]
Looks good on QA!
