### ISSUE TITLE
Design refinements: Feature and About pages (sidebar and widget styling)

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#180]
## Sidebar (left nav)
- [x] Prevent menu items from shifting position between active and non-active states (currently they shift slightly, [see menu here as an example](https://localhost:21407/demo/feature/feature-page-examples))
- [x] About sidebar: Left nav menu items should be all upper case like parent items on Curated Features left nav

## Standard Widgets
See [Standard Widgets](https://localhost:21407/demo/feature/standard-widgets) page for examples of all widgets in use
- [x] Quote widget - update styling to [match quote styling on this page](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=molecules-rich-text)
- [x] Horizontal Rule widget - update styling to [match bottom horizontal rule style of the quote](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=molecules-rich-text)
    - [x] We have a border for borders (#afafaf) so I tried that first as it's less harsh than the black line
    - [x] I also increased the margin above and below to give each section more spacing 
- [x] Uploaded Item Row widget - Remove border line, update caption text to [match style on this page](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=molecules-rich-text) (do not include the camera icon), [use this button style for View Larger button](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=atoms-button-as-outline), in the View Larger viewer remove gray boarder and match HL styling if exists.
- [x] [In edit mode](https://staging-harvard-curiosity.notch8.cloud/spotlight/exhibit3/feature/standard-widgets/edit), for the Uploaded Item Row widget, either decrease the font size of the word 'Remove' or increase its container so the 'e' does not wrap [see screenshot](https://user-images.githubusercontent.com/60190174/176684729-e81336c0-e0f5-466c-8e31-4929dce2eb2f.png). This happens with many other [exhibit widgets](https://localhost:21407/demo/feature/exhibit-item-widgets/edit) as well.
   - [x] Maura made the width of the remove container larger and decrease font-size 

## Exhibit Widgets
See [Exhibit Widgets](https://localhost:21407/demo/feature/exhibit-item-widgets) page for examples of all widgets in use
- [x] For the Browse Categories, Browse Group Categories, Saved Searches, and Pages widgets use the same card styling as on the collections landing and Browse pages.
- [x] Item Row widget
   - [x] Remove the border line. 
- [x] Slide carousel widget
   - [x] Use same styling for slide caption as used for title hover in masonry view. 
- [x] Item Slideshow widget - Update nav styling to match theme. Recommendations on other styling improvements?

**Comment by mferrarini** [comment]
Pulling out the unfinished tasks and moving this to Harvard QA for the rest to be tested.

**Comment by VanessaVenti** [comment]
Looks good on QA!
