### ISSUE TITLE
Design refinements: Browse pages and layouts

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#182]
## Browse
- [x] Update exhibit tag button styling to [Button As Outline](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=atoms-button-as-outline)] and use the same gray color of its hover state as its active state. (consistent with what we see on homepage)
- [x] Update styling subtitle on [browse page](https://localhost:21407/demo/browse/wooden-objects) to Lora italic
- [x] Enable hyperlinking in browse description text on [browse page](https://localhost:21407/demo/browse/wooden-objects). If this one is not an easy fix, it is a lower priority and can be bumped out into a separate story. It may require updates to the admin dashboard. (find an example of this)
   - [x] As you are typing in the "long description" text box, you type `<a href="#url">Link text</a>` and the text will appear as a hyperlink
- [x] “Search within this browse category” search box [](([example](https://localhost:21407/demo/browse/ceramics)))
    - [x] text all on one line
    - [x] formatting search box
    - [x] truncating titles?

## Browse category cards
- [x] [Browse landing page cards](https://localhost:21407/demo/browse)
    - [x] Smaller text for category caption (title + item-count) + no shadow
    - [x] Hover treatment - adjusts so happens on link hover
- [x] [Browse cards on other pages](https://localhost:21407/contagion)
    - [x] Remove light gray border + border-radius
    - [x] Give background a darker linear-gradient (like see on homepage) `linear-gradient(rgba(0, 0, 0, 0.08), rgba(0, 0, 0, 0.714)), url("https://curiosity-qa.lib.harvard.edu/images/1091/604,512,1240,929/800,600/0/default.jpg")`

**Comment by VanessaVenti** [comment]
Looks good on QA!
