### ISSUE TITLE
Design refinements: item detail page

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#183]
## Item detail page
- [x] Pager (appears in top right if you've done a search before getting to an item)
    - [x] Make numbers trueno font and smaller
    - [x] Remove underline
    - [x] Change “back to search” to “back to search results” and styled like HDC (left-aligned link)?
    - [x] Make sure the left and right links are in line with one another
- [x] Edit button - give padding/margin below (same space as above)
- [x] ~~Prevent table text from overlapping on smaller screens (happens with Creator/Contributor)~~ *this won't be an issue once the spaces are added on VV's side
- [x] PDS objects sometimes cut off a portion of the top right menu items (see https://curiosity.lib.harvard.edu/contagion/catalog/36-990013573930203941 for an example). Experiment with “Take a tour of the view” align-left and “Full screen” align-right or just have "Full screen" link centered bc viewer will be changing soon enough? (Note: note going to fix the old viewer, hopefully this will be a non-issue once Mirador 3 is applied; instead of the sidebar, will place the "Open in Mirador" link centered below viewer, like where the "Take a tour" link is on HDC)
- [x] Right sidebar - style more like HGL sidebars
    - [x] more padding
    - [x] bold titles
    - [x] smaller font
- [x] Mobile view
    - [x] keep title OPEN (HDC as an example)
    - [x] adjust padding for other item categories
- [x] Edit view
    - [x] Needs some reworking

## Item detail page on 'No Thumbnail Or Viewer' theme
- [x] Remove viewer/viewer space. For example see [IOHP item in 2.0 (no viewer space)](https://curiosity.lib.harvard.edu/iranian-oral-history-project/catalog/32-adamiyatt__tahmouress01) vs [IOHP item in 3.0 (has empty viewer space)](https://curiosity-qa.lib.harvard.edu/iohp/catalog/18-ADAMIYATT__TAHMOURESS01)

**Comment by mferrarini** [comment]
Pulling out the unfinished tasks and moving this to Harvard QA for the rest to be tested.

**Comment by VanessaVenti** [comment]
Looks good in QA!
