### ISSUE TITLE
Design refinements: search experience

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#184]
## Limit your search filters
- [x] Remove hanging space below each button (coming from card margin)
- [x] Update carrots to be solid red triangles
- [x] Change carrot direction behaviors
    - [x] Closed = pointing down
    - [x] Expanded = pointing up
- [x] "More" link is showing double arrows, use the solid one and remove other
- [x] Confirm that font styles and sizes all match HDC and HGL
    - [x] Numbers should be smaller and dark gray
    - [x] Items should be a little bigger with gray underline on hover
    - [x] Normalize spacing between categories
    - [x] Selected item
        - [x] check the font size
        - [x] close button icon with red hover state
- [x] Selected facet (at top of page): darker text

## Results: All views
- [x] Truncate titles after 75 characters not counting white spaces in all views except for item detail view *used css to truncate to 2 lines
- [x] “Start Over” button
    - [x] Change to a link that says 'Clear All' like HDC
    - [x] Place below selected filters/facets - kept this to the right of the selected facets
![](https://user-images.githubusercontent.com/60190174/184983639-55d700ba-88a1-4e00-a96a-6c5503f6cf69.png)
- [x] When no results are found, update page with the same language as seen in the [HDC no results page](https://digitalcollections.library.harvard.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=ixtacuixtla).
- [x] When no results are found, update pagination language to read "No entries found" (currently reads "Showing 1 to 0 results")

## Results: Masonry view
- [x] Use same title hover styling as HDC (example)
    - [x] small black trueno font
    - [x] opaque white background
    - [x] title at bottom of image
    - [x] no underline on text hover
- [x] Thumbnails should have padding below each image so they don't stack directly on top of each other
- [x] [When facets display after conducting a search](https://curiosity-qa.lib.harvard.edu/spotlight/demo/catalog?view=masonry&exhibit_id=demo&search_field=all_fields&q=wood), display 4 columns of images. Image width should expand to fill the column (minus padding) and the image height should be the full height of the image.
- [x] [When facets don't display such as on a Browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=masonry), display 5 columns of images. Image width should expand to fill the column (minus padding) and the image height should be the full height of the image.

## Results: List view on 'No Thumbnail Or Viewer' theme
[See IOHP on QA as an example for each of these:](https://curiosity-qa.lib.harvard.edu/iohp/catalog?search_field=all_fields)
- [x] Remove result numbers for each item
- [x] Shift metadata results left (to space where thumbnail would be or wherever you think is best!)
- [x] Remove view type toggles (results will only be viewable in list view)

## Results: List view on browse page
- [x] [For list view on a browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=list), center the image column OR increase the left margin of the image column OR make two columns and center them - what do you think would look best? This one is a lower priority, so leave it to the end if it isn't a quick update :).

## Results: Gallery view on browse page
- [x] [For Gallery view on a browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=gallery), center the four columns of images. This one is a lower priority, so leave it to the end if it isn't a quick update :).

**Comment by VanessaVenti** [comment]
Removed:
`- [ ] Search results total number of items is not appearing - should display something like 'Showing 25 to 36 of 107 results'`
because it was fixed in https://github.com/harvard-lts/CURIOSity/issues/179

**Comment by mferrarini** [comment]
Pulling out the unfinished tasks and moving this to Harvard QA for the rest to be tested.

**Comment by VanessaVenti** [comment]
Looks good on QA!
