### ISSUE TITLE
Update harvester email notifications

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#185]
## Summary

In 2.0, if not all items successfully harvest the overall job will still be successful and the notification email will list any items that failed to harvest.

In 3.0, the job will say it failed even though it successfully harvested most items. The email does not include the items that failed, but it can be figured out by going to the exhibit's dashboard.

Could 3.0 behave more similarly to 2.0? It is confusing to see that a job failed when it may be only one item that did not harvest. If at least the success/failed message behavior was the same that'd be great. A bonus would be to add the items that didn't harvest to the email (or at least a notification that not items harvested), but as long as they are easily identifiable via the dashboard that's fine.

## Testing Instructions (Developer)

1. Run `git checkout jeremyf---harvard-lts---CURIOSity#185-part-2` 
2. Download [this git diff](https://drive.google.com/file/d/1elej6H9i8XXLVTfvM4qMfqEO9b_EQH5P/view?usp=sharing) 
3. Move the file to where your project loads the [spotlight-oaipmh-resources](https://github.com/harvard-lts/spotlight-oaipmh-resources) gem 
4. Run `git apply patch.diff` 
5. Reload gem (if necessary) 
6. Login as an admin 
7. Navigate to the new harvester form 
8. Fill out the required fields for the demo set 
9. Submit the form 
10. Verify the Acceptance Criteria 

## Acceptance Criteria 
- [x] The "recent indexing activity" modal displays error information 
- [x] The job has the status of "Successful" (less than half of the items should fail) 
- [x] An email is sent containing the total number of harvest errors

**Comment by bkiahstroud** [comment]
@VanessaVenti how many items need to fail to tip the job from Successful to Failed?

**Comment by VanessaVenti** [comment]
@bkiahstroud good question! In 2.0 I've only see 1 o2 two items fail at a time at most and it is pretty rare. I'm not sure if things will be different with the new harvester. So maybe if it is more than half the items in a job it would fail?

**Comment by jeremyf** [comment]
Below is my information gathering notes regarding the mailers that are in the OAI gem, Spotlight, v2 Curiosity, and v3 Curiosity.  I'll have more to discuss/ask questions about but wanted to put this here as a placeholder.

In the OAI PMH gem:

-   The [Spotlight::HarvestingCompleteMailer](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/mailer/spotlight/harvesting_complete_mailer.rb#L1) has the delivery methods for:
    -   `harvest_indexed`, which renders [app/views/spotlight/harvesting<sub>complete</sub><sub>mailer</sub>/harvest<sub>indexed.html.erb</sub>](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/views/spotlight/harvesting_complete_mailer/harvest_indexed.html.erb)
    -   `harvest_failed`, which renders [app/views/spotlight/harvesting<sub>complete</sub><sub>mailer</sub>/harvest<sub>failed.html.erb</sub>](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/views/spotlight/harvesting_complete_mailer/harvest_indexed.html.erb)
-   The `Spotlight::HarvestingCompleteMailer#harvest_indexed` is called:
    -   In [Spotlight::Resources::PerformHarvestJobs](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/jobs/spotlight/resources/perform_harvests_job.rb)
-   The `Spotlight::HarvestingCompleteMailer#harvest_failed` is called:
    -   In [Spotlight::Resources::PerformHarvestJobs](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/jobs/spotlight/resources/perform_harvests_job.rb)
    -   In [Spotlight::Resources::OaipmhHarvesterController#create](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/7ceec0f74d0f459e135ba11f5798c8d9d0acbbdc/app/controllers/spotlight/resources/oaipmh_harvester_controller.rb#L8-L36)

In the v2 Curiosity:

-   The [Spotlight::IndexingCompleteMailer](https://github.com/harvard-library/Curiosity/blob/b1751692aa580bfd03341268d9797d2c0aa4c4db/app/mailers/spotlight/indexing_complete_mailer.rb#L1-L14) has the delivery method for:
    -   `documents_indexed`, which renders [app/views/spotlight/indexing<sub>complete</sub><sub>mailer</sub>/documents<sub>indexed.html.erb</sub>](https://github.com/harvard-library/Curiosity/blob/b1751692aa580bfd03341268d9797d2c0aa4c4db/app/views/spotlight/indexing_complete_mailer/documents_indexed.html.erb).
-   The [Spotlight::AddUploadsFromCSV](https://github.com/harvard-library/Curiosity/blob/b1751692aa580bfd03341268d9797d2c0aa4c4db/app/jobs/spotlight/add_uploads_from_csv.rb#L1-L39) calls the `Spotlight::IndexingCompleteMailer` regardless of status; I’m not seeing where it would have listed failed items in the harvest.

In the v3 Curiosity:

-   There are no custom mailers

In the current Spotlight:

-   The [Spotlight::IndexingCompleteMailer](https://github.com/projectblacklight/spotlight/blob/ebed5d6cd5413427d431e2db0705745ce648fff6/app/mailers/spotlight/indexing_complete_mailer.rb#L1-L15) has the delivery methods for:
    -   `documents_indexed`, which renders [app/views/spotlight/indexing<sub>complete</sub><sub>mailer</sub>/documents<sub>indexed.html.erb</sub>](https://github.com/projectblacklight/spotlight/blob/ebed5d6cd5413427d431e2db0705745ce648fff6/app/views/spotlight/indexing_complete_mailer/documents_indexed.html.erb).  This now includes a section that renders the errors encountered.
    -   This mailer is an updated version of what v2 Curiosity has
-   The [Spotlight::AddUploadsFromCSV](https://github.com/projectblacklight/spotlight/blob/ebed5d6cd5413427d431e2db0705745ce648fff6/app/jobs/spotlight/add_uploads_from_csv.rb) calls the `Spotlight::IndexingCompleteMailer` regardless of status.

**Comment by phil-plencner-hl** [comment]
@bkiahstroud @jeremyf 
The acceptance criteria does not pass for me after following the instructions.

The job fails and does not complete. It says there are 76 indexed items, but the job status itself is "failed" and not "success".

Additionally, it did not send me an email notification of the failure.
Full trace of the harvest below.

`

1 | job started | September 13, 2022 18:15
-- | -- | --
job created by philip_plencner@harvard.edu |  
47-990006049270203941_RADSCHL:1267673 did not index successfully: |  
pizza |  
47-990019020820203941 did not index successfully: |  
pizza |  
47-990048483550203941 did not index successfully: |  
pizza |  
47-990093974220203941 did not index successfully: |  
pizza |  
47-HUAM153614soc_URN-3:HUAM:OCP13112_DYNMC did not index successfully: |  
pizza |  
47-HUAM323801_URN-3:HUAM:INV170468_DYNMC did not index successfully: |  
pizza |  
47-W279060_URN-3:FHCL:546127 did not index successfully: |  
pizza |  
47-W387573_URN-3:HPREWARD:1182401 did not index successfully: |  
pizza |  
47-W387837_URN-3:HPREWARD:1182456 did not index successfully: |  
pizza |  
47-W387865_URN-3:HPREWARD:1182484 did not index successfully: |  
pizza |  
47-W387881_URN-3:HPREWARD:1182498 did not index successfully: |  
pizza |  
47-W387940_URN-3:HPREWARD:1182545 did not index successfully: |  
pizza |  
47-W388046_URN-3:HPREWARD:1182585 did not index successfully: |  
pizza |  
47-far00033c00025 did not index successfully: |  
pizza |  
47-wid00001c00073 did not index successfully: |  
pizza |  
47-wid00001c00236 did not index successfully: |  
pizza |  
47-wid00001c00262 did not index successfully: |  
pizza |  
47-wid00001c00268 did not index successfully: |  
pizza |  
47-wid00001c00273 did not index successfully: |  
pizza |  
47-wid00001c00281 did not index successfully: |  
pizza |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-990006049270203941_RADSCHL:1267673 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-990019020820203941 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-990048483550203941 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-990093974220203941 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-HUAM153614soc_URN-3:HUAM:OCP13112_DYNMC |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-HUAM153634soc_URN-3:HUAM:OCP13166_DYNMC |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-HUAM19416soc_URN-3:HUAM:OCP12742_DYNMC |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-HUAM323801_URN-3:HUAM:INV170468_DYNMC |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-HUAM57865soc_URN-3:HUAM:OCP10673_DYNMC |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W279060_URN-3:FHCL:546127 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W387573_URN-3:HPREWARD:1182401 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W387837_URN-3:HPREWARD:1182456 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W387865_URN-3:HPREWARD:1182484 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W387881_URN-3:HPREWARD:1182498 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W387940_URN-3:HPREWARD:1182545 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-W388046_URN-3:HPREWARD:1182585 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-arn00007c00040 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-ecb00010c00030 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-far00033c00025 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-gra00002c00044 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-orc00002c00093 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00002 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00045 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00073 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00104 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00132 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00170 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00212 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00236 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00240 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00259 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00260 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00261 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00262 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00263 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00264 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00266 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00267 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00268 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00269 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00270 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00271 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00272 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00273 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00274 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00275 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00276 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00277 |  
Missing Spotlight::SolrDocumentSidecar for document_id=47-wid00001c00281 |  
processed 76 / 96 |  
job failed | September 13, 2022 18:15

`

**Comment by phil-plencner-hl** [comment]
@jeremyf @bkiahstroud 
Spoke too soon, it did send me an email after all with the total number of failed items. Nevertheless, the job itself is still listed as a "failure". Not sure this is correct? I have checked the two acceptance criteria that has passed.

```
Your harvest has just finished being processed.

The demo set has been indexed from the harvest and added to the exhibit CURIOSity Demo Site .

The harvester encountered 20 errors. See the harvester logs for details.
```

**Comment by phil-plencner-hl** [comment]
@jeremyf @bkiahstroud I also just want some confirmation about the errors for the sidecars. For example, in my list of errors there is this one: 
`Missing Spotlight::SolrDocumentSidecar for document_id=47-arn00007c00040`

Looking at the 76 items indexed, it does appear to be there. I'm not entirely sure what Spotlight defines as a "Sidecar" but I thought it had to do with the thumbnail images? In the case of this item I see the thumbnail so I'm not entirely sure what is supposedly missing.

At any rate, I believe the expected behavior is to index the item even if the sidecar fails (this is how it works in CURIOSity 2.0), so this _should_ be correct. If so, these would be considered warnings, and I'm wondering if they should be highlighted differently (yellow?) in the dashboard.

But I was suspicious about why I was seeing the thumbnail when the sidecar fails...

Thanks!

cc: @enriquediaz @VanessaVenti

**Comment by phil-plencner-hl** [comment]
@jeremyf @bkiahstroud 
FYI:
I harvested a different exhibit (crimes) and with the git diff it performs similar simulated failures. However it ends as a success:
processed 469 / 587 

Perhaps something is off with how it considers half? It still ends in a failure for the demo exhibit:
processed 76 / 96

**Comment by bkiahstroud** [comment]
@phil-plencner-hl Jeremy and I found a bug where the errors weren't being counted correctly, leading to the job saying Failed instead of Successful. That should be fixed now. 

Also, the messages related to the Sidecars have been converted from errors to warnings. 

--- 

> I'm not entirely sure what Spotlight defines as a "Sidecar" but I thought it had to do with the thumbnail images?

A Sidecar is the middleman between an item and Solr: 

```
Item (Spotlight::Resources::OaipmhUpload) --> "Sidecar" (Spotlight::SolrDocumentSidecar) --> Solr
```

In Rails terms, it's an association -- item `has_many` sidecars (although each item should only ever have one sidecar). The sidecar is what actually gets indexed into Solr. 

The following warning indicates that an Item with the identifier `arn00007c00040` should have had a sidecar created for it (i.e. been indexed in Solr), but no sidecar was found for that identifier.

```
Missing Spotlight::SolrDocumentSidecar for document_id=47-arn00007c00040
```

**Comment by phil-plencner-hl** [comment]
@bkiahstroud Thank you! I just tested it out and it works as described.
