### ISSUE TITLE
Update FTS message wording

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#196]
Update the wording and styling when someone checks the 'Search inside text of items' checkbox as [shown in this mock-up](https://www.sketch.com/s/39eb3859-75e8-4add-8498-6cbf2934d73c/a/52E7VyE) (screenshot below):
- [x] Update message at the top of the search results to say: You searched INSIDE TEXT OF ITEMS for: [search term] / Your search includes results from inside text of items. [Search metadata instead.](url)
- [x] ~Hide facets and instead display message saying 'Limiters not available while searching inside text of items'~ Split to #202 
- [x] Hide number of items per page dropdown
- [x] Hide List/Gallery/Masonry buttons
- [x] Remove pagination at the bottom of the page and instead add a 'Load more results' button

![Screen Shot 2022-09-15 at 4 31 43 PM](https://user-images.githubusercontent.com/60190174/190502997-7601014b-389e-47c4-95b9-c08abe6466f3.png)

**Comment by dl-maura** [comment]
We don't currently have a notification/textbox for when you don't check the FTS box, so I suspect that may be more involved than the other part which is just changing a label. Below is a non-fts search

![Screen Shot 2022-09-13 at 1 42 29 PM](https://user-images.githubusercontent.com/61880785/189973132-0a1fcedc-e90d-4294-97ce-efcb77a2d836.png)

**Comment by sephirothkod** [comment]
I think #206  should have taken care of the rest of this ticket.

**Comment by VanessaVenti** [comment]
@mferrarini - all of these are done except for the first one which is just to update the wording and should hopefully be quick!

**Comment by dl-maura** [comment]
I can do this if it isn't in another branch already, just a label change it looks like?

**Comment by VanessaVenti** [comment]
Looks good on QA!
