### ISSUE TITLE
YAML updates

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#199]
- [x] Update [curiosity.yml on Github](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/harvard_yaml_mapping_files/mods/curiosity.yml) with https://drive.google.com/file/d/18DaA-aY5Tua9g0d80MyTF_W-0rTIgxsA/view?usp=share_link
- [x] Remove curiosity-BTA.yml from Spotlight QA

# [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/harvard_yaml_mapping_files/mods/curiosity.yml) updates
- [x] Merge the lastest version of the yaml that Robin is working on for BTA. (VV merged on 12/5/2022)
- [x] Update Additional Digital Items to pull in all DOs greater than 1 (Robin has added this to her version so it will get merged when the BTA changes are merged)
- [x] Update **date_tesim** and **date_ssim** to match **creation-date_tesim** and **creation-date_ssim** respectively

The following fields can be removed from [curiosity.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/job_entry/harvard_yaml_mapping_files/mods/curiosity.yml) (if present):
- [x] creation-date_tesim (use date_tesim instead)
- [x] spotlight_upload_date_tesim (use date_tesim instead) (Does not appear in curiosity.yml)
- [x] spotlight_upload_attribution_tesim (use attribution_tesim instead) (Does not appear in curiosity.yml)

# [jbsd.yml](https://github.com/harvard-lts/spotlight-oaipmh-resources/blob/main/harvard_yaml_mapping_files/mods/jbsd.yml) updates
- [x] Add Additional Digital Items to pull in all DOs greater than 1
- [x] Update full and thumbnail fields to only display 1 like in curiosity.yml

**Comment by dl-maura** [comment]
Ongoing

**Comment by VanessaVenti** [comment]
@dl-maura - just a heads up, Robin is going to send along an updated version of the yaml with changes for BTA soon so we'll want to make sure any changes we make are synced in the version Robin is working on.

**Comment by VanessaVenti** [comment]
@dl-maura - I just uploaded [the lastest version of the yaml that Robin is working](https://drive.google.com/file/d/1YbkMyaeEl2kBMSOicQLuAAEqgQ_IdaAO/view?usp=sharing) on to the Shared Resources folder. She says new additions all need to be tested and that the two “TO DO”s are yet to come. So she'll likely make another update to this file. But that's where it is whenever it makes sense to merge it with the one you edited and upload to Github.

**Comment by VanessaVenti** [comment]
@dl-maura - the curiosity.yml linked above on Google drive now has the BTA changes/additions and is ready to be pushed to Github.

**Comment by VanessaVenti** [comment]
Looks good on Github and QA!
