### ISSUE TITLE
Harvest from Solr Sets

### ISSUE THREAD

**Issue by dl-maura** [harvard-lts/CURIOSity#219]
We now have the solr harvests ready, but we don't see in the UO the ability to harvest from Solr. @bkiahstroud This existed in the oai gem before, I am not sure if the work here is just 'enabling' it in the Spotlight instance, or if this needs to be ported over to main from the older branch.

# Harvesting info
### Base URL
http://libsearch8elb-prod.lib.harvard.edu:18280/solr (for Harvard for permanent use)
https://fts.lib.harvard.edu/solr (for Softserve for temporary use)

### Set specs > alias
 tedming > ming
 acat-calendar > acats-calendars
 acat-faculty > acats-faculty
 acat-courses > acats-courses

# Acceptance criteria
The metadata and facets in the following exhibits in 3.0 QA all match their 2.0 prod equivalents:  
- [x] [Ming QA](https://curiosity-qa.lib.harvard.edu/index-ming-dynasty-chinese-paintings) vs [Ming Prod](https://curiosity.lib.harvard.edu/index-ming-dynasty-chinese-paintings)
- [x] [Calendars QA](https://curiosity-qa.lib.harvard.edu/archived-harvard-university-online-course-catalogs-calendars) vs [Calendars Prod](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-calendars)
- [x] [Faculty QA](https://curiosity-qa.lib.harvard.edu/archived-harvard-university-online-course-catalogs-faculty) vs [Faculty Prod](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-faculty)
- [x] [Courses QA](https://curiosity-qa.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses) vs [Courses Prod](https://curiosity.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses)
   - [x] All items but 1 harvested. Data for all items that harvested looks good.
   - [ ] Should we reharvest all or ask Anthony to put that one in a set? Got the following error:
   `136-d8bd95ea06858f67204607b6668184c1 did not index successfully:`
    `execution expired (Delayed::Worker.max_run_time is only 14400 seconds) `
   `Missing Spotlight::SolrDocumentSidecar for document_id=136-D8BD95EA06858F67204607B6668184C1`
   - [ ] Also [Search page](https://curiosity-qa.lib.harvard.edu/archived-harvard-university-online-course-catalogs-courses/search_configuration/edit) broke when trying to edit facets. Edit successfully went through. This has happened a couple times before on other pages in 2.0 where Dee Dee was able to fix the page on the back end.

# Documentation and clean up
- [x] Set specs were given aliases to for naming consistency since renaming them is a much heavier lift: https://github.com/harvard-lts/CURIOSity/issues/240
- [x] Document Base URL (http://libsearch8elb-prod.lib.harvard.edu:18280/solr) and set specs here https://wiki.harvard.edu/confluence/pages/viewpage.action?spaceKey=libdsi&title=CURIOSity+Collections
- [x] Create ticket to clean up set specs (https://github.com/harvard-lts/CURIOSity/issues/240)

**Comment by dl-maura** [comment]
curl "https://fts.lib.harvard.edu/solr/acat-calendar/select?q=*:*&wt=json"

**Comment by bkiahstroud** [comment]
Related PRs: 

- https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/43 
- https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/187
