### ISSUE TITLE
Whitespace after URN is throwing harvester error

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#224]
The following 11 items from **saef** did not harvest:

- [x] hou00084c00044 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211924 "
- [x] hou00110c00046 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211934 "
- [x] hou00124c01701 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:100182660 "
- [x] hou00124c01702 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:100182841 "
- [x] hou00387c00193 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211908 "
- [x] hou00387c00632 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211998 "
- [x] hou00387c02650 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101212029 "
- [x] hou00497c01306 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101212035 "
- [x] hou01325c00069 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211965 "
- [x] hou01325c00134 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101211982 "
- [x] hou01466c00082 - bad URI(is not URI?): "https://nrs.harvard.edu/URN-3:FHCL.HOUGH:101212126 "

Our 2.0 harvester accepted these and I believe the 3.0 harvester did as well at one point bc I believe I successfully harvested saef in 3.0 before. I can have the curator clean up these records so they will harvest, but I wondered if we should allow the 3.0 harvester to accept them as warnings and not errors? (Especially if the space doesn't break anything in the UI that seems fine to me.) And/or should the harvester clean up the training whitespace?

**Comment by bkiahstroud** [comment]
Related PR: https://github.com/harvard-lts/spotlight-oaipmh-resources/pull/44

**Comment by annapaulinevs** [comment]
All 11 items are searchable in 3.0.
