### ISSUE TITLE
Add new default fields

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#231]
New fields are being added to the curiosity.yml for BTA. Most are exhibit specific, but a few we want to add as defaults for all collections:

### Biographical / Historical Note
- [x] Solr field name: biographical-historical-note_tesim
- [x] Display label: Biographical / Historical Note
- [x] Display order: After Notes
- [x] Check box for: Item details

### Identifier
- [x] Solr field name: unit-id_tesim
- [x] Display label: Identifier
- [x] Display order: After Container
- [x] Check box for: Item details

### Normalized Date
- [x] Solr field name: normalized-date_ssim
- [x] Display label: Normalized Date
- [x] Display order: After Date
- [x] Check box for: NA (We will only show this as a facet for some ASpace only collections instead of the Date facet. More work needs to be done to get this to work for Alma records)

# Testing instructions

1. Once the new fields are set up, harvest the following set to a new exhibit:
Type: MODS
Base URL: https://api-qa.lib.harvard.edu/oai/
Set name: bta
Mapping: [curiosity.yml](https://drive.google.com/file/d/18DaA-aY5Tua9g0d80MyTF_W-0rTIgxsA/view?usp=share_link) (this is the updated one with BTA changes pending pushing to Github, see #199 for status)

2. In Search > Facets, check box for Normalized Date so it will display
3. Check record GUT5000C00014 in PUI to make sure all fields are populated

**Comment by phil-plencner-hl** [comment]
I added the fields following the documentation:
https://docs.google.com/document/d/17xDHQs8BnNbxQuw1UDQujOf0QCUAXahKbgPqfHnEIbo/edit#heading=h.x7pioqdqao13

However, it doesn't seem to work when creating a new exhibit and harvesting BTA.

Here is the commit, in the `add-default-fields` branch:
https://github.com/scientist-softserv/harvard-curiosity/commit/87124244f996e3847a31bda75084fbefda5ddacb

cc: @dl-maura

**Comment by phil-plencner-hl** [comment]
Working. PR is here:
https://github.com/scientist-softserv/harvard-curiosity/pull/20

**Comment by VanessaVenti** [comment]
Looks good on QA!
