### ISSUE TITLE
Investigate multi-valued check box

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#239]
This is new to 3.0. When importing 2.0 exhibits this check box does NOT get checked and can not be changed (at least via the admin UI) after importing the json. See discussion about this check box in previous tickets linked below:

https://github.com/harvard-lts/CURIOSity/issues/107
https://github.com/harvard-lts/CURIOSity/issues/170

# Outstanding questions
- [x] Should we add "is_multiple": true for the index fields? (We want to make sure we aren’t overwriting anything if we don’t add it)
  - For defaults we’re not sure but we don’t care (ssim means multivalued). Multi-value fields appear to be working as expected on exhibits using JSON imports without adding this. This check box is likely not relevant for our workflow since we harvest items. It only appears to make a difference for items that are created/edited manually which we have no plans to do.
- [x] Should we add "is_multiple": true to the custom fields in the json before uploading? (We want to confirm we aren't overriding settings on import.)
  - Probably not necessary, but might be a good idea just in case as these fields do behave a little differently than the default fields. The do appear to be working in 3.0 Q.A though, see Annotator in JSBD.
- [x] When should we check this box going forward for new fields? Is it best to always check it just in case?
  - Yes, probably best to check it just in case, but again it likely isn't necessary/doesn't have an impact on our workflow since we harvest items.

This check box is located under Metadata > Add new field:
![Screen Shot 2022-11-03 at 12 30 26 PM](https://user-images.githubusercontent.com/60190174/199778923-f209316f-66c0-4166-9e1b-9c6ddbc5e483.png)

**Comment by dl-maura** [comment]
We have to manually edit the json
