### ISSUE TITLE
Clean up data collection set specs

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#240]
The current set specs for the Solr data collections are inconsistent and should be renamed as follows:

- [x] tedming > ming
- [x] acat-calendar > acats-calendars 
- [x] acat-faculty > acats-faculty 
- [x] acat-courses > acats-courses

Once the set specs are updated:
- [x] Document the new set specs here: https://wiki.harvard.edu/confluence/pages/viewpage.action?spaceKey=libdsi&title=CURIOSity+Collections

**Comment by VanessaVenti** [comment]
@dl-maura will put in a ticket dev ops to create aliases for the set specs above.

**Comment by dl-maura** [comment]
Ticket is in!

**Comment by VanessaVenti** [comment]
Successfully harvested acats-calendars using the alias!
