### ISSUE TITLE
Add links to facetable metadata fields

### ISSUE THREAD

**Issue by mferrarini** [harvard-lts/CURIOSity#245]
In all search results and item detail views, add links to facetable metadata fields. There are 16 default facet fields and some exhibits have custom facetable fields as well. Note: this has been requested for BTA which has some custom facetable fields. 

Ideally, we'd like every facetable field to automatically have this behavior without having to create and maintain a list of these fields. This would be any metadata field that has the "Controlled vocabulary" box checked in the Admin UI and shows up under the Search > Facets section (only if checked?). In Solr, this would be any SSIM field.  

Example record in CNA where subjects are hyperlinked: https://colonialnorthamerica.library.harvard.edu/spotlight/cna/catalog/990006017170203941

Facetable default fields to create links for:

- [ ] Creator / Contributor (This doesn't work in the item detail view bc we display a tesim here instead that is slightly different from the corresponding ssim. We could consider creating a second tesim to use instead if it is desirable to have this field be a clickable link in the metadata view)
- [x] Place of Origin
- [x] Publisher
- [x] Date
- [x] Language
- [x] Genre
- [x] Culture
- [x] Style / Period
- [x] Material / Technique
- [x] Subject
- [x] Place
- [x] Series
- [x] Collection
- [x] Digital Format
- [x] Repository
- [x] Available To

**Comment by mferrarini** [comment]
In all search results and item detail views,  add links to facetable metadata fields like DCP does (i.e. subjects).

This has also been requested for BTA.

- [ ] place of origin
- [ ] language
- [ ] subjects
- [ ] genre
- [ ] repository

**Comment by phil-plencner-hl** [comment]
Some notes....

Blacklight has a way to toggle the link_to_facet for particular fields:
https://geoblacklight.org/tutorial/2015/02/09/customize-your-application.html

We're doing this in HGL:
https://github.com/harvard-lts/Harvard-Geospatial-Library/blob/main/app/controllers/catalog_controller.rb#L138-L145

But this doesn't seem to work the same way in Spotlight. I believe it is because the UI is handling these settings on an exhibit-by-exhibit basis.

Princeton has a solution where they updated the Metadata admin page to include a checkbox for "link to search" on each metadata field. We may need to follow their example:
https://github.com/pulibrary/dpul/pull/623

cc: @enriquediaz @VanessaVenti @dl-maura

**Comment by phil-plencner-hl** [comment]
PR is here: https://github.com/scientist-softserv/harvard-curiosity/pull/29

**Comment by VanessaVenti** [comment]
Looks good in QA! All fields in the list above work aside from Creator / Contributor which is to be expected bc we display a tesim version of this field on the item detail page. Ideally, the Link to Search checkbox could be moved to the Search > Facets list as only these fields can be made actionable.
