### ISSUE TITLE
Investigate fielded (advanced) searching options

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#25]
As a an advanced researcher/curator, I would like to be able to further refine my searches through fielded search. As a curator, this would allow me to create refined browse topics to highlight topics within the collection to better serve researchers.

[Fielded search documentation](https://docs.google.com/document/d/17xDHQs8BnNbxQuw1UDQujOf0QCUAXahKbgPqfHnEIbo/edit#heading=h.boqvgqm0r0bq)

### Outstanding questions:
- [x] Can we rename "Everywhere" to "All fields"? Is this a base spotlight issue? (made a ticket to expand box)
  - Probably same issue as Exhibit Tags (note you can’t change it in the UI)
  - Could override core spotlight to change this, might be a bunch of files you need to change, but would have to look
  - Upgrading in the future could be more difficult
- [x] If there is both a tesim and ssim, which should we use? Does it matter if the data is the same for both? (Currently only the creator_contributor-ssim has different data than its tesm counterpart.)
  - Doesn’t make a difference unless there IS different data.
  - Suggest we make a decision so you have consistency (so like decide we always use ssim or tesim). Since we always have a tesim field, but not always a ssim field we can always use tesim.
- [x] Are there recommended weights to use for single and multiple fields? General info about the weights would be helpful.
  - If just 1 you shouldn't need to add weight because there isn’t a competitive field
  - Are weights the higher priority? We think so. We could also ask AM
 

The fielded searches we would like to enable are: All fields, Title, Creator, Subject, Genre

**Comment by dl-maura** [comment]
Can this be closed?

**Comment by VanessaVenti** [comment]
@dl-maura I added our outstanding questions to the description so we don't loose track of them, but they may move to new tickets.

**Comment by dl-maura** [comment]
Everywhere is in a ticket so closing this
