### ISSUE TITLE
Widgets fixed in 3.0

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#251]
### Item Row
- [x] Increase the default size. Images appear very small on the page, the default size should be larger. (This was fixed by pulling in larger thumbnails.)

### Uploaded Item Row
As a curator, I would like the Uploaded Item Row widget to:
- [x] optionally turn the image into a link to easily connect researchers to the source of the object shown in the image (resolved in 3.0)
- [x] wrap the text next to an image in this widget like the Exhibit Item Row widget does (see: https://curiosity.lib.harvard.edu/american-currency/feature/continental-currency). (resolved in 3.0)
- [x] not have a border - looks particularly noticeable/awkward when a singe image is centered on a page, see: https://curiosity.lib.harvard.edu/south-sea-bubble/feature/the-founding-of-the-south-sea-company (resolved as part of design updates)
- [x] have a 'view larger' button to open zoomable viewer. (resolved in 3.0)

### Search Results
- [x] Fix styling issues of extra metadata displaying (resolved in 3.0) - When using the search results widget and only the gallery or masonry views are selected, extra metadata appears in the display. Both of these views are only supposed to display the title. This is particularly problematic when only the masonry view is selected as the extra metadata makes it not possible to click on an item to get to the item detail page. The current workaround is to select the list view in addition to the gallery and/or masonry views, this seems to resolve the issue. However, there is a bug with this option where sometimes the list/gallery/masonry icons are blue when not selected and they should always be black.

### Pages
- [X] Make size of the Pages widget tiles the same size regardless of the number. Currently different size tiles will display based on the number tiles in a row. (resolved as part of design updates)

### Item Slideshow
- [x] Increase the default size. Images appear very small on the page, the default size should be larger. (This was fixed by pulling in larger thumbnails.)

### Carousel
- Fix image quality and style with HL elements. (This was fixed by pulling in larger thumbnails and design updates.)

**Comment by VanessaVenti** [comment]
The above widget updates were requested in 2.0 and were resolved as part of the 3.0 upgrade itself or a combination of the upgrade plus pulling in larger thumbnails and design updates.
