### ISSUE TITLE
Delete a harvest from an exhibit

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#257]
Test and document deleting a harvest from an exhibit.

### Instructions

- [ ] Harvest two different set specs to an exhibit
- [ ] Delete all items from one set spec from both Solr and Mysql
- [ ] Confirm only the items from the other set spec remain in the exhibit UI
- [ ] Document the process on the wiki for Prod Ops to follow for production

**Comment by VanessaVenti** [comment]
@dl-maura is testing this and will write documentation on it

**Comment by dl-maura** [comment]
https://wiki.harvard.edu/confluence/display/LibraryTechServices/Clearing+a+Mistaken+Harvest

**Comment by dl-maura** [comment]
@VanessaVenti @enriquediaz @phil-plencner-hl if my documentation seems ok we can close this

**Comment by VanessaVenti** [comment]
I'll leave this one up to someone with better Solr knowledge to confirm these instructions are good to go :)
