### ISSUE TITLE
Metadata mapping enhancements

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#314]
## Botanical Illustrations
- [ ] Year only facet for Aspace records. Still want date to appear as 2023-03-17 in item detail view. Example records: [FAR00031C00007](https://api.lib.harvard.edu/v2/items?recordIdentifier=FAR00031C00007) and [ORC00002C00003](https://api.lib.harvard.edu/v2/items?recordIdentifier=ORC00002C00003). See if Normalized Date can be enhanced to only display first 4 digits. Also investigate what is needed to get this to work for Alma records.
- [ ] Place/Location information as a facet. For example, see https://hollisarchives.lib.harvard.edu/repositories/22/archival_objects/2447883 where Collected at Winter Pond, Winchester, Massachusetts
  - [ ] Could this be added in Aspace as a location that would be facetable in CURIOSity and follow DACs? 
  - [ ] If not, a tag or a canned search might work instead
- [ ] [Notify requestor](https://docs.google.com/document/d/1OFXpYxSBCp9BtO6UK3xMlg4TxCs4EmMOFbFey1iMorY/edit#heading=h.638fddi1o00m)

## Black Teacher Archive (BTA)
- [ ] Title - Display Title before Volume and Number. Need to look at examples from all record types as this will effect all CURIOSity collections.
  - [ ] Reharvest most heavily effected collections?
- [ ] Configure Archival Series (archival-series_ssim and archival-series_tesim) - currently does not work
- [ ] [Notify requestor](https://docs.google.com/document/d/1OFXpYxSBCp9BtO6UK3xMlg4TxCs4EmMOFbFey1iMorY/edit#heading=h.638fddi1o00m)

**Comment by VanessaVenti** [comment]
Moved to https://github.com/harvard-lts/CURIOSity/issues/328
