### ISSUE TITLE
Item Show Page Layout & Footer Link Update

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#72]
# Summary
- update the layout of the item show page to match the mockups
- update the footer links to match the links below.

From Vanessa:

Hi [@Summer](https://assaydepot.slack.com/team/U02SG739U4U) - here are the mocks for the [item show page](https://www.sketch.com/s/39eb3859-75e8-4add-8498-6cbf2934d73c/p/E520AF2C-557F-4FD6-A28D-3F7753D751CE). A few things to note:
This is based off the same page in HDC, here is the [HDC repo](https://github.com/harvard-library/HarvardDigitalCollections) for whatever code you're able to reuse
Unlike HDC, we'd like all fields to be expanded by default. Adding the ability to showing fewer is a lower priority
The Contact info we'd like to pull in from Spotlight's contact widget
I updated the links in the footer in this (and all mock ups) - here are the URLs to use:
[Terms of Use](http://curiosity.lib.harvard.edu/terms-of-use)
[HOLLIS](https://hollis.harvard.edu/)
[HOLLIS for Archival Discovery](https://hollisarchives.lib.harvard.edu/)
[Harvard Digital Collections](https://library.harvard.edu/digital-collections)
[Report a problem](http://nrs.harvard.edu/urn-3:hul.ois:digitalcollections)
[CURIOSity Services](http://nrs.harvard.edu/urn-3:hul.eresource:curiosityservice)
[Staff log in](https://curiosity.lib.harvard.edu/users/sign_in)

# Acceptance criteria
- [x] the top controls section matches the mockup (back to search link etc)
- [x] the metadata is styled per the mockup
- [ ] ~~tools and related items section~~ (will be completed in this ticket: https://github.com/harvard-lts/CURIOSity/issues/77)
- [x] the contact widget is added on the right side
- [ ] ~~more like this section~~ (will be completed in this ticket:  https://github.com/harvard-lts/CURIOSity/issues/78)
- [x] the footer links match the mockup (and link to the URLs above)

**Comment by summer-cook** [comment]
### QA - passed. This work is on staging

![screencapture-staging-harvard-curiosity-notch8-cloud-spotlight-exhibit3-catalog-3-1-2022-05-18-15_23_46](https://user-images.githubusercontent.com/73361970/169149371-0c455e4f-4c82-46c1-93ed-beedc73b017c.png)
