### ISSUE TITLE
Item show page: tools & related links

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#77]
# Summary
The tools and related links section on the item show page needs several links added after harvesting is working

From Vanessa:
Many of the Tools & Related Links are pulling links from other parts of the site:
The Download This Item dropdown, Copy Manifest Link, and Open in Mirador links are all coming from the embedded Mirador viewer for each item - I'm guessing we will hold off on hooking those up until we have harvesting working
Permalink and the More Item Detail links are metadata fields that would normally be displayed on the left that we'd like moved here instead - I'm guessing we will also hold off on hooking those up until we have harvesting working
The only link that doesn't change from item to item is [What is IIIF?](https://iiif.io/community/faq/)

# Related
https://github.com/harvard-lts/CURIOSity/issues/72

# Screenshot
<img width="365" alt="Screen Shot 2022-05-16 at 9 03 06 AM" src="https://user-images.githubusercontent.com/73361970/168610648-ebc63ecd-a809-4ebe-a430-4e9f0eada293.png">

# Acceptance Criteria
- [x] All links in this section work as expected, and this section contains all the links from the mockup
- [x] Links should only appear in sidebar when they are checked off in exhibit dashboard --> metadata table --> item detail column

## Top section
- [x] Download this item dropdown -- dropdown menu options are different for ids and pds objects
- [x] Permalink

## MORE ITEM DETAILS
- [x] Harvard Art Museums: permalink-ham_tesim
- [x] HOLLIS Record: hollis-record_tesim
- [x] Finding Aid (default is set to not display) (Exhibit Dashboard -> Metadata -> Item details unchecked by default): finding-aid_tesim
- [x] Finding Aid Component: finding-aid-component_tesim

## IIIF
- [x] Copy manifest link
- [x] Open in Mirador link (move this to below Mirador viewer, like where the "Take a tour" link is on HDC, change language to "Open full screen viewer")
- [x] What is IIIF link

**Comment by dl-maura** [comment]
Can investigate how we did this in HDC but this may be de-prioritized given the updates coming to Viewer?

**Comment by dl-maura** [comment]
full_image_ssm

**Comment by phil-plencner-hl** [comment]
for the download button. Here is the HDC code:
https://github.com/harvard-library/HarvardDigitalCollections/blob/harvard-master/app/views/catalog/_show_default.html.erb

Here is a PDS example item:
https://localhost:21407/demo/catalog/47-990014631980203941

Here is an IDS example item:
https://localhost:21407/jacques-burkhardt-scientific-drawings/catalog/33-ARC_209-001

Looking at the iiif_manifest item in the solr records is likely the best bet. It uses a URN, but will resolve to the right URL. After doing so we can try to parse the url and see if `info.json` can be appended to the manifest url. If it can, then it is IDs, if it cannot then it is PDS. 

After determining that, we can likely use the exact same code from HDC to build the download button.

It's probably also a good idea to ask MPS team if any of these assumptions will change after their rollout. If these assumptions are no longer correct, we will also have to fix HDC because it will break!

**Comment by phil-plencner-hl** [comment]
Committed to the branch. Appears to be working:

https://github.com/scientist-softserv/harvard-curiosity/commit/7edbe390f2cfcb9a85fd16312f779c71b5e78273

**Comment by VanessaVenti** [comment]
Looks good in QA!
