### ISSUE TITLE
Design refinements - take 1

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#82]
### Exhibit landing page

- [x]  Allow full exhibit description to display. I think our longest description should fit on the card at the current font size, but I will test once it no longer trims it.
- [x]  Update exhibit tag button styling to [Button As Outline](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=atoms-button-as-outline)] and use the same gray color of its hover state as its active state.

### All pages

- [x] Increase body (and hyperlink) font size to 19px
- [x] Hide breadcrumbs
- [x] Update list styling to [match list styling on this page](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=molecules-rich-text)

### Left Nav

[See mock up for examples of updates listed below](https://www.sketch.com/s/39eb3859-75e8-4add-8498-6cbf2934d73c/a/WKVqQpg )
- [x] For parent menu items, the increased spacing between letters should remain the same whether active or not and also remain all caps
- [x] For child menu items, letters should be proper case at all times
- [x] Underline should persist for items when active

### Search results
**All views** 

- [x] Use the button styling as seen on [this page](https://digitalcollections.library.harvard.edu/catalog?q=trees&search_field=all_fields&utf8=%E2%9C%93&view=list). This search can also be used as a guide for all other search results updates listed below except when noted otherwise.
- [x] Increase thumbnail width to 180px. Ideally, max height would also be limited to 180px for List and Gallery views too, but Masonry view would be 180px wide by full height of the image (as it is currently). Let me know if that is not possible and we can figure out alternatives.

**List view** 

- [x] Increase title to 18px
- [x] Increase left margin of the field labels and reduce right margin 
- [x] Remove colon at the end of field labels

**Gallery view** 

- [x] Increase title size to 18px and move title and all other fields below the image

**Masonry view** 

- [x] Hide all metadata fields and only display title on hover
- [x] Display thumbnails in 3 columns stacking the next row of images directly under the image above it

**Browse**

- [x] Update [browse card subtitle](https://staging-harvard-curiosity.notch8.cloud/spotlight/exhibit3/browse) font to be white Lora italic (like other subtitles
- [x]  Update exhibit tag button styling to [Button As Outline](https://harvard-library-web-team.gitlab.io/Harvard-Patterns/?p=atoms-button-as-outline)] and use the same gray color of its hover state as its active state.
- [x] Update styling for title and subtitle on [browse page](https://staging-harvard-curiosity.notch8.cloud/spotlight/exhibit3/browse/browse-all-items) to match styles on other pages
- [x] Remove columns in description

### About

- [x] In the left nav, underline should persist on active menu item

### Admin dashboard

- [x] Currently the left nav changes style when Feature Pages or About Pages is selected. Using the same style as all the other pages would be ideal. See screenshots below:

**Feature and About Pages nav**
![Image](https://user-images.githubusercontent.com/60190174/169612035-37363051-b8f4-45bf-8081-d88463de5b58.png)

**All other pages nav**
![Image](https://user-images.githubusercontent.com/60190174/169612012-eee2359d-737c-4456-ad93-13a7da10ca2f.png)

**Comment by summer-cook** [comment]
@VanessaVenti 
in regards to this point:

Headings - [Follow these guidelines (scroll down to the Font Styles section)](https://library.harvard.edu/brand-guidelines#typography). However it appears Spotlight is not generating the appropriate heading level. The exhibit name in the header is correctly rendered as an H1, the page title is also an H1 and should be an H2, headings within the page are H2s and should be H3s, and headings within a widget's text are H3s and should be H4s. Let us know the level of effort on this one and how you'd recommend fixing it (ideally it should be fixed in the core).

- this shouldn't be too hard to fix, but will just require overriding the out-of-the-box spotlight views to change the markup.

**Comment by summer-cook** [comment]
Hi @VanessaVenti Vanessa- for the point
-  Increase left margin of the field labels and reduce right margin

did you mean you want just the labels to mave a greater left margin and not the title? just want to clarify here. I am noticing that the field labels in Harvard Digital Collections are in line with the title. There is also not a ton of margin between the thumbnail and the metadata in HDC. the top is a screenshot of curiosity & below is HDC. thank you!

<img width="975" alt="Screen Shot 2022-06-02 at 1 42 48 PM" src="https://user-images.githubusercontent.com/73361970/171703272-7cef9895-b0a7-45c6-963d-d0239eb59e4a.png">
<img width="731" alt="Screen Shot 2022-06-02 at 1 42 59 PM" src="https://user-images.githubusercontent.com/73361970/171703277-df4b6476-9e82-45ee-808d-b1e17abed654.png">

**Comment by summer-cook** [comment]
Also- for the gallery view, i tried making the thumbnails all 180px in width, but it looked a little big odd with a lot of spacing. I came up with this solution instead which makes the thumbnails 180px in height, but responsive widths depending on the screen size.

https://share.getcloudapp.com/KoujL4q1

Let me know if that works!

**Comment by VanessaVenti** [comment]
@summer-cook - For gallery view, we think this works for now, but want to see how this will look when we have actual collection thumbnails as cropping has historically been an area of concern among curators.

**Comment by VanessaVenti** [comment]
@summer-cook - Hi again - I just updated the ticket with the button styling to use :).

**Comment by summer-cook** [comment]
Increase thumbnail width to 180px. Ideally, max height would also be limited to 180px for List and Gallery views too, but Masonry view would be 180px wide by full height of the image (as it is currently). Let me know if that is not possible and we can figure out alternatives.
 
 --> for this one, I did the following
 
**List view:** 180px width x 180px height, thumbnails are all square and set to this size to look more consistent:
<img width="1175" alt="Screen Shot 2022-06-06 at 11 49 25 AM" src="https://user-images.githubusercontent.com/73361970/172207294-f723eb13-6d16-4c19-a1bf-4a979696dcf1.png">

**Gallery View:** 
maximum of 180px height, width varies based on screensize to allow responsive breaking of columns/ columns to take up full width of screen (shown in video above that was approved)

Masonry view
max-width: 180, height varies based on image height.

**Comment by VanessaVenti** [comment]
Hi @summer-cook - I finally had a chance to look over all these. Overall, things are looking really good! I think this story is good to go for now and [I've started a new one](https://github.com/harvard-lts/CURIOSity/issues/83) with refinements based on this round.
