### ISSUE TITLE
Headings- override from out of the box spotlight

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#86]
- [x] Headings - [Follow these guidelines (scroll down to the Font Styles section)](https://library.harvard.edu/brand-guidelines#typography). However it appears Spotlight is not generating the appropriate heading level. The exhibit name in the header is correctly rendered as an H1, the page title is also an H1 and should be an H2, headings within the page are H2s and should be H3s, and headings within a widget's text are H3s and should be H4s. Let us know the level of effort on this one and how you'd recommend fixing it (ideally it should be fixed in the core). 

In our check in on 6/1 we said: 

This request is more on Spotlight side, and the true fix is submitting an update to spotlight core. The priority is staying on time with schedule so we will go with the overrides. We will: 
- [x] Will do a local override 
- [x] Make a ticket to submit back (post-accessibility review): https://github.com/harvard-lts/CURIOSity/issues/258

**Comment by VanessaVenti** [comment]
@mferrarini  According to Cory Lown (from Stanford), he says to ask about approving PRs in the #blacklight channel of code4lib.

**Comment by mferrarini** [comment]
Updating the task list for this ticket

- [ ] Keep track of inappropriate use of h1's and h2's, but do a local override to have them look like h2's and h3's respectively
- [ ] Homepage page-title disappears from HTML when uncheck the "Show title" box (Edit -> Options); have page-title h1 persist, but add sr-only class when curators don't want to show the title

**Comment by mferrarini** [comment]
Maura F's notes for when we revisit this and hopefully change in spotlight core:

Keeping track of h1’s and h2’s
// h1's to h2's
// spotlight/dashboards/show.html.erb
// spotlight/pages/show.html.erb
// spotlight/browse/show.html.erb
// spotlight/browse/index.html.erb *added in an h2


// h2's to h3's
// _page_activity.html.erb
// _reindexing_activity.html.erb
// _solr_document_activity.html.erb 


// _site_sidebar.html.erb changed from h4 to h2


// .blacklight-catalog-show

**Comment by VanessaVenti** [comment]
Change H2s to look like H3s on all pages. Change H3s to look like H4s (only an option within a widget).

**Comment by mferrarini** [comment]
PR: https://github.com/scientist-softserv/harvard-curiosity/pull/9

**Comment by VanessaVenti** [comment]
Looks good on QA!
