### ISSUE TITLE
Design refinements - take 3

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#90]
### Admin dashboard
- [ ] Add exhibit ID back under General, see screenshot of 2.0 below: <img width="1050" alt="Screen Shot 2022-08-11 at 4 54 14 PM" src="https://user-images.githubusercontent.com/60190174/184240477-2063d7d8-07a2-4d86-a11c-76e20dc3e711.png">
- [ ] Move Tags and Bulk updates under curation and make sure they show up under the Curator user mask role. They were originally there, but we moved them temporarily because we weren't sure if we would enable this feature.
- [ ] Under Bulk updates > Download CSV, change check box defaults so that Visibility is UNchecked and Tags is CHECKED. (Curators are much more likely to update Tags rather than Visibility). If this is difficult to find /update in the code, this task is a low priority so it can be left to the end. 
- [ ] Under Browse > Edit browse category> Hide the Masthead tab so curators cannot change the masthead for a browse category. This is bad practice from a usability standpoint.

### All Search Results Views
- [ ] Must (requested for BTA): Add links to facetable metadata fields like DCP does (i.e. subjects)
- [ ] Truncate titles after 75 characters not counting white spaces in all views except for item detail view
- [ ] View icons appear to be slightly different from HDC, match HDC view icons
- [ ] Prepend 'Search Term:' to search terms that appear at the top of the results after doing a keyword search and change Start Over button to a link that says 'Clear All' like HDC, see image below for both examples: <img width="246" alt="Screen Shot 2022-08-16 at 4 53 36 PM" src="https://user-images.githubusercontent.com/60190174/184983639-55d700ba-88a1-4e00-a96a-6c5503f6cf69.png">

**Masonry view**
- [ ] Use same title hover styling as HDC
- [ ] When there is no thumbnail, the title should appear instead
- [ ] Thumbnails should have padding below each image so they don't stack directly on top of each other
- [ ] [When facets display after conducting a search](https://curiosity-qa.lib.harvard.edu/spotlight/demo/catalog?view=masonry&exhibit_id=demo&search_field=all_fields&q=wood), display 4 columns of images. Image width should expand to fill the column (minus padding) and the image height should be the full height of the image.
- [ ] [When facets don't display such as on a Browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=masonry), display 5 columns of images. Image width should expand to fill the column (minus padding) and the image height should be the full height of the image.

### List view on browse page
- [ ] [For list view on a browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=list), center the image column OR increase the left margin of the image column OR make two columns and center them - what do you think would look best? This one is a lower priority, so leave it to the end if it isn't a quick update :).

### Gallery view on browse page
- [ ] [For Gallery view on a browse page](https://curiosity-qa.lib.harvard.edu/spotlight/demo/browse/wooden-objects?view=gallery), center the four columns of images. This one is a lower priority, so leave it to the end if it isn't a quick update :).

### Item Detail Page
- [ ] Change “back to search” to “back to search results” and styled like DCP (left-aligned link)

### Exhibit Widgets
- [ ] Item Row widget - Remove the border line. The View Larger button does not work for this widget, likely because of our IIIF incompatibility - should we hide this option from the Admin UI or just tell curators not to use it? Or we could gray it out so we remember that it is an option if we ever want to turn it on again when/if we are IIIF compatible? Getting the button to work is a low priority if it is not a quick fix. 
- [ ] Slide carousel widget - Use same styling for slide caption as used for title hover in masonry view. Image quality is better with higher res thumb, but still not great - Summer updated the harvester to pull in 600px thumbs so we'll see if that fixes this issue and/or causes other performance issues.
- [ ] Item Embed widget - Does not work. Curators use this widget currently so it should be fixed.
- [ ] Item Slideshow widget - Update nav styling to match theme. Recommendations on other styling improvements?
- [ ] Item Grid widget - Image quality is better with higher res thumb, but still not great - Summer updated the harvester to pull in 600px thumbs so we'll see if that fixes this issue and/or causes other performance issues.
- [ ] Search Results widget - Icons should match HDC view icons. Also, if a user chooses different display mode (list/gallery/masonry) they are popped back up to top of page. Instead, the user should remain on the same point on the page when switching between views. This widget is not used often, so fixing it is a lower priority.

**Comment by jeremyf** [comment]
> Truncate titles after 75 characters not counting white spaces in all views except for item detail view

In the above you can use Blacklight's `helper_method` https://github.com/projectblacklight/blacklight/wiki/Blacklight-configuration ; see https://github.com/harvard-lts/CURIOSity/issues/147

**Comment by mferrarini** [comment]
All design refinements mentioned here have been moved to other tickets.
